export const userConstants = {    

    USER_SIGNIN_REQUEST : 'USER_SIGNIN_REQUEST',
    USER_SIGNIN_FAIL :'USER_SIGNIN_FAIL',   
    USER_SIGNIN_SUCCESS:'USER_SIGNIN_SUCCESS',
    USER_LOGOUT : 'USER_LOGOUT',
    
    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGUP_SUCCESS: 'USER_SIGUP_SUCCESS',
    USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
    
    GETPROFILE_BYID_REQUEST : 'GETPROFILE_BYID_REQUEST',
    GETPROFILE_BYID_SUCCESS : 'GETPROFILE_BYID_SUCCESS',
    GETPROFILE_BYID_SUCCESS : 'GETPROFILE_BYID_SUCCESS',

    UPDATE_USER_ACCOUNT_REQUEST : 'UPDATE_USER_ACCOUNT_REQUEST',
    UPDATE_USER_ACCOUNT_SUCCESS : 'UPDATE_USER_ACCOUNT_SUCCESS',
    UPDATE_USER_ACCOUNT_FAIL : 'UPDATE_USER_ACCOUNT_FAIL'
    
}
